install.packages("remotes")
install.packages("plotly")
library(remotes)
install_version("ggplot2", version="3.3.6")
install_version("reshape2", version="1.4.4")
install_version("dplyr", version="1.0.9")
install_version("caret", version="6.0.93")
install_version("tidymodels", version="1.0.0")
install_version("htmlwidgets", version="1.5.4")
install_version("optparse", version="1.7.3")
